### ISSUE TITLE
Translate F-Droid and Play Store description

### ISSUE THREAD

**Issue by airon90** [markusfisch/BinaryEye#31] opened 2019-05-16 07:33 UTC
As the title say, the description of the app in the stores is hardcoded in English. Make it translatable, please.

**Comment by urbalazs** [comment] 2020-03-07 21:56
This issue is the duplicate of https://github.com/markusfisch/BinaryEye/issues/87, where the problem is described more detailed.

**Closed** 2020-03-08 09:27 UTC
