### ISSUE TITLE
Special characters display error

### ISSUE THREAD

**Issue by Grafenea** [markusfisch/BinaryEye#342] opened 2023-01-01 16:39 UTC
Characters such as " ç " and " ã ", are displayed as a diamond with a question mark (?) in the middle.

**Comment by markusfisch** [comment] 2023-01-01 17:59
Hm, this shouldn't happen, of course. Thanks for filing an issue 👍 

Unfortunately, I cannot reproduce the issue 😬  The following QR code contains the quoted characters and seems to work well:
![test](https://user-images.githubusercontent.com/485246/210180360-b37773f6-5cbb-40b1-b1b7-372c568d8784.png)

Does it work on your device?

Would you mind sharing the original barcode that shows the effect?

**Comment by Grafenea** [comment] 2023-01-07 15:14
The coded text in qr code works, but in PDF417 it showed an error.

![pdf417](https://user-images.githubusercontent.com/121762566/211157432-85571855-5415-44b9-bd03-1dff155576ea.png)

In other codes such as datamatrix and aztec code it worked perfectly, only PDF417 did not. And sorry for not specifying what code I was using earlier.

**Comment by markusfisch** [comment] 2023-01-08 16:40
Thanks for the clarification! 👍 

There was some special text conversion for PDF417 codes that is no longer necessary.
Fixed in https://github.com/markusfisch/BinaryEye/commit/e79ad49d1512fb973c95e308d0834ea35f8334be

There will be a new version soon.

**Closed by markusfisch** 2023-01-08 16:40 UTC
