### ISSUE TITLE
Errors reading vCards

### ISSUE THREAD

**Issue by SnejPro** [markusfisch/BinaryEye#326] opened 2022-12-01 21:48 UTC
I wrote my own QR code generator website: https://cdn.snejp.de/qrcode/

I recognised two errors occuring when i scan generated vCards with BinaryEye.

## Types in TEL, EMAIL and ADR were not handled correctly

Following RFC 6350 (https://www.rfc-editor.org/rfc/rfc6350#section-6.4.1), TEL, EMAIL, and ADR can include a TYPE parameter that specifies, for example, whether the phone number is a home or work number.
But when i scan the QR code with Binary Code, the follow is recognised:
![git_screen_1](https://user-images.githubusercontent.com/11321022/205164491-277283c0-b5be-4478-9660-59424927c599.jpg)
![git_screen_2](https://user-images.githubusercontent.com/11321022/205164511-c07d6d83-7981-415b-979c-35c5a4b4d29f.jpg)

## Adding a contact does not contain the address
This could be an Android error, as it also occurs at https://play.google.com/store/apps/details?id=com.google.zxing.client.android.

![git_screen_3](https://user-images.githubusercontent.com/11321022/205164526-8cbf85e6-f8ad-4f89-a460-9faad4bc5939.jpg)

**Comment by cyb3rko** [comment] 2023-05-16 12:41
I can confirm issues with vCards.
In my case the address is found, but it has added some newlines.

Furthermore I have the same issues with telephone and address types.

---
That's what the Google Camera finds:

<img src="https://i.imgur.com/FlfzIyV.jpg" width=300>

And that's what Binary Eye finds:

<img src="https://i.imgur.com/pUrtRfk.jpg" width=300>

The raw content:

<img src="https://i.imgur.com/GCzlPWU.jpg" width=300>

---

So explicitly including the TYPE keyword is not working.  
If you remove the TYPE keyword and just write WORK, it's working.

Most likely applies to @SnejPro case as well.  
The RFC includes the TYPE keyword in the example, but almost every real-life example just drops that keyword, I don't know why.

**Comment by markusfisch** [comment] 2023-05-20 11:23
Thanks for reporting this! 👍 And sorry for the late answer.

I will try to sort this out as soon as I find some time.

**Comment by clst** [comment] 2023-08-28 17:29
Hi there. Thanks for the great app. Just a quick question: since this issue is still open:
Does Binary Eye do the complete parsing (into an Intent) because there is no mechanism for vcards in Android or because importing a vcard does not give the user an interface to select anything about the import process?

**Comment by markusfisch** [comment] 2023-09-01 13:00
@clst Yes, VCard's are parsed [here](https://github.com/markusfisch/BinaryEye/blob/master/app/src/main/kotlin/de/markusfisch/android/binaryeye/actions/vtype/vcard/VCardAction.kt#L34), and no, there's no UI to let a user manually interfere.

**Comment by markusfisch** [comment] 2023-10-13 21:51
Fixed in https://github.com/markusfisch/BinaryEye/commit/c604ad5ef234ee4c2ef37c4548afd97c989185d1

Version 1.61.0 is on it's way through Google Play and should become available soon.

**Closed by markusfisch** 2023-10-13 21:51 UTC
