### ISSUE TITLE
Wi-fi QR codes with certain text at the end are not recognized as Wi-Fi QR codes

### ISSUE THREAD

**Issue by nickyivyca** [markusfisch/BinaryEye#331] opened 2022-12-07 06:06 UTC
I generated a QR code for my wi-fi network using https://app.qr-code-generator.com/, and Binary Eye does not recognize it as a wi-fi QR code, it only picks it up as raw text. It seems like the metadata at the end is possibly throwing it off, since Binary Eye can pick up other wi-fi codes just fine. I compared it to some other wi-fi QR codes and there's an extra bit of text at the end:
`WIFI:T:WPA;S:[ssid];P:[password];H:0`
Another QR code that is recognized as Wi-fi by Binary Eye:
`WIFI:T:WPA;S:[ssid];P:[password];`

I made a sample QR code here that other QR code apps (including Android's built in wi-fi QR code scanner) can recognize just fine but Binary Eye just reads it as basic text.
![My_WiFi_QR_Code (1)](https://user-images.githubusercontent.com/3387157/206100987-4c60f9ef-9347-4e6e-891e-a4d3933edeae.png)

**Comment by markusfisch** [comment] 2022-12-07 11:27
Thanks for filing an issue about this! 👍 The problem is not the metadata but that the expression is not terminated with a semicolon 😬 

I've just updated the code to simply complete these expressions with the missing semicolon now (in https://github.com/markusfisch/BinaryEye/commit/bd9da5889c89dff812a70160f2fa7ef3e71e2c40).

So this will be fixed in the next update.

**Closed by markusfisch** 2022-12-07 11:27 UTC
