### ISSUE TITLE
QR-Code can not be scanned

### ISSUE THREAD

**Issue by SnejPro** [markusfisch/BinaryEye#308] opened 2022-10-29 20:44 UTC
Hi,

with Version 1.54.1 i can not scan this QR-Code:

![qrcode](https://user-images.githubusercontent.com/11321022/198851600-406403b5-770b-4b07-be96-66aee2281bfc.svg)

But when i remove two characters from the url in the QR-Code, it works:

![qrcode2](https://user-images.githubusercontent.com/11321022/198851640-dd673ad8-5220-4f5d-a9dd-eac3a0a57f37.svg)

Greetings

Jens

**Comment by markusfisch** [comment] 2022-10-30 12:08
Hm, that's odd! 🤔 Thank you very much for filing an issue! 👍 This is definitely a bug!

Version 1.53.x migrated from the original Java implementation of [ZXing](https://github.com/zxing/zxing) to the [C++ fork of ZXing](https://github.com/zxing-cpp/zxing-cpp). The reasoning behind this change is that the C++ fork is much faster and, more importantly, an active project that offers new features and barcode formats (such as support for Micro QR Codes). The Java implementation is in "maintenance mode", meaning there are only bug fixes and minor enhancements.

Now, I can confirm that the ZXing C++ fork currently fails to read the first QR Code. I don't know why that is the case but I am investigating this issue.

**Comment by markusfisch** [comment] 2022-10-30 13:21
Fixed with an update to the latest version of ZXing C++.

Version 1.55.0 should become available soon.

**Closed by markusfisch** 2022-10-30 13:21 UTC

**Comment by SnejPro** [comment] 2022-10-30 14:01
Now it works, thank you. When will the new version be in fdroid?

**Comment by markusfisch** [comment] 2022-10-30 20:13
Hard to say - usually F-Droid updates at midnight so the app _should_ be available tomorrow on F-Droid. But I noticed longer delays before so it might well be another day or so.

You can also get the app directly from GitHub if you want:
https://github.com/markusfisch/BinaryEye/releases
